id: bsds500_affine_shift
segSaveDir: results
BSDS500_root: /home/nepe/etit_arbeit/data_sets/bsds500/BSR/BSDS500/data
mode: test
nImages: 200.0
xLabel: Horizontal and Vertical Shift in Pixel
affine_trafo:
- name: t_0
  parVal: 0
  T:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.0, 0.0, 1.0]
- name: t_1
  parVal: 1
  T:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [1.0, 1.0, 1.0]
- name: t_5
  parVal: 5
  T:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [5.0, 5.0, 1.0]
- name: t_10
  parVal: 10
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [10.0, 10.0, 1.0]
- name: t_20
  parVal: 20
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [20.0, 20.0, 1.0]
- name: t_25
  parVal: 25
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [25.0, 25.0, 1.0]
- name: t_30
  parVal: 30
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [30.0, 30.0, 1.0]
- name: t_40
  parVal: 40
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [40.0, 40.0, 1.0]
- name: t_50
  parVal: 50
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [50.0, 50.0, 1.0]
- name: t_60
  parVal: 60
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [60.0, 60.0, 1.0]
- name: t_70
  parVal: 70
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [70.0, 70.0, 1.0]
- name: t_80
  parVal: 80
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [80.0, 80.0, 1.0]
- name: t_90
  parVal: 90
  T:
  - [1.0, 0.0,  0.0]
  - [0.0, 1.0,  0.0]
  - [90.0, 90.0, 1.0]
- name: t_100
  parVal: 100
  T:
  - [1.0, 0.0,   0.0]
  - [0.0, 1.0,   0.0]
  - [100.0, 100.0, 1.0]