id: bsds500_affine_shear
segSaveDir: results
BSDS500_root: /home/nepe/etit_arbeit/data_sets/bsds500/BSR/BSDS500/data
mode: test
nImages: 200.0
xLabel: Shear Factor
affine_trafo:
- name: s_0
  parVal: 0.0
  T:
  - [1.0,  0.0, 0.0]
  - [0.0, 1.0,  0.0]
  - [0.0,  0.0,  1.0]
- name: s_0_01
  parVal: 0.01
  T:
  - [1.0,  0.01, 0.0]
  - [0.01, 1.0,  0.0]
  - [0.0,  0.0,  1.0]
- name: s_0_025
  parVal: 0.025
  T:
  - [1.0,   0.025, 0.0]
  - [0.025, 1.0,   0.0]
  - [0.0,   0.0,   1.0]
- name: s_0_05
  parVal: 0.05
  T:
  - [1.0,  0.05, 0.0]
  - [0.05, 1.0,  0.0]
  - [0.0,  0.0,  1.0]
- name: s_0_1
  parVal: 0.1
  T:
  - [1.0,  0.1, 0.0]
  - [0.1, 1.0,  0.0]
  - [0.0,  0.0,  1.0]
- name: s_0_25
  parVal: 0.25
  T:
  - [1.0,  0.25, 0.0]
  - [0.25, 1.0,  0.0]
  - [0.0,  0.0,  1.0]
- name: s_0_5
  parVal: 0.5
  T:
  - [1.0, 0.5, 0.0]
  - [0.5, 1.0, 0.0]
  - [0.0, 0.0, 1.0]

